run_modules:
  - fastqc
  - star
  - salmon
  - bbduk
extra_fn_clean_exts:
  - type: regex_keep
    pattern: "A{2}[0-9]+_meta_info.json"
use_filename_as_sample_name: true
sp:
  fastqc/zip:
    fn: "*_fastqc.zip"
  bbduk:
    fn: "*.bbduk.log"
  salmon/meta:
    fn: "*_meta_info.json"
